### ISSUE TITLE
Orthogonal optimization of IOS and TVM  (inter+intra)

### ISSUE THREAD

**Issue by Kyrie-Zhao** [mit-han-lab/inter-operator-scheduler#12]
Hi, I am wondering how can we implement the orthogonal design of inter+intra optimization based on TVM+IOS. Seems that so far we can only  transform IOS Graph->TVM Relay with no schedule info.

**Comment by yaoyaoding** [comment]
Hi Zhao,

You could try this framework: https://github.com/awslabs/raf
This framework is based on TVM (and Relay), and it supports multi-stream execution on CUDA platform.

Here is the multi-stream support wiki: https://github.com/awslabs/raf/blob/main/docs/wiki/3_dev_guide/pass/Multi-CUDA-Stream-Schedule.md

**Comment by Kyrie-Zhao** [comment]
> 

Thanks for the recommendation. Seems that RAF does not support edge GPU such as Jetson series right?

**Comment by yaoyaoding** [comment]
Seems RAF developers have not tested on edge devices yet, as it is designed for training. Thus you might encounter some engineering issues running it on edge device. But there should no fundamental problem that prevent you from using RAF on CUDA-enabled edge devices, as far as I know.

**Comment by yaoyaoding** [comment]
Close due to inactivity. Please reopen this issue if you have any other questions.
