### ISSUE TITLE
parameter 'profile_stage' causes different latency result when using graph_latency

### ISSUE THREAD

**Issue by Lucas890512** [mit-han-lab/inter-operator-scheduler#13]
Hello. I am using ios to optimize squeeze_net.  After ```ios.optimize()```, ```ios.ios_runtime.graph_latency``` is used to check the latency. 

When i use ```profile_stage=True```, the latency is 0.74ms and when I set it to ```False```, the latency is 0.64ms.

Does ```profile_stage``` have some impact on the latency measurement?

```python
graph=ios.models.squeezenet()
latency , dd  = ios.ios_runtime.graph_latency(optimized_graph, batch_size=1, repeat=6, profile_stage=True)
latency   = ios.ios_runtime.graph_latency(optimized_graph, batch_size=1, repeat=6, profile_stage=False)
```

**Comment by yaoyaoding** [comment]
Yes, the profile stage would inject the cudaEvents after each stage to record time stamps, which has an impact on the latency.

See 
https://github.com/mit-han-lab/inter-operator-scheduler/blob/91963c06051c58c7b92e8ec57a5a98788b5f4c01/src/ios/ios_runtime.cu#L1297-L1315
(when profile_stage=True, the record_events in the C++ would be set to true)

**Comment by Lucas890512** [comment]
OK, thx for the explanation! Does it mean that setting profile_stage=True will get an incorrect latency (become larger) ? And it should be set to false when I want to make an accurate measurement ?

**Comment by yaoyaoding** [comment]
Yes, there is an overhead to measure the stage latency. If you want to have an accurate end-to-end latency, you should set profile_stage=False.

**Comment by Lucas890512** [comment]
Alright, thx. I've noticed another phenomenon. When getting the latency of greedy schedule of Squeeze_net, `Profile=True` return a smaller latency than `Profile=False`. The result is like:

```
unprofile:  0.8923733135064443
unprofile:  0.8938524623711904
unprofile:  0.8891475598017374
unprofile:  0.8902897735436758
unprofile:  0.888701319694519
unprofile:  0.8910453220208486
unprofile:  0.8232275148232778
unprofile:  0.8216382165749868
unprofile:  0.92449422677358
unprofile:  0.8264977832635244
profile:  0.8012817601362864
profile:  0.8025253514448801
profile:  0.8015839954217275
profile:  0.8047351042429606
profile:  0.8027573227882385
profile:  0.8002364337444305
profile:  0.8016053438186646
profile:  0.8026702304681143
profile:  0.8005270957946777
profile:  0.8022453188896179
```

The code is  :
```python
def main():
    graph = ios.models.squeezenet()

    graph.greedy_schedule(8)
    for i in range(10):
        latency = ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6)
        print("unprofile: ",np.mean(latency))
    for i in range(10):
        latency,z= ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6,profile_stage='True')
        print("profile: ",np.mean(latency))

```

I am kinda confused. Can I ask what causes this result ?

**Comment by yaoyaoding** [comment]
That's an interesting phenomenon. 

There are two ways to synchronize the kernels on different streams:
(1) do something (include recording an event) on default stream (the stream = 0), or
(2) call synchronization function (cudaDeviceSyncrhonize or sync stream)

The first method relies on the default stream behavior, see https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html

When I was developing IOS, I found these two methods are similar in terms of performance (cuda 10.2, cudnn 7.6.5) on the workload I was working on. Thus, I chose the second method (L1312). But for profiling the stage, I have to use stream to record time stamp, thus, in the profiling mode, I used the stream to do the synchronization.

Seems that in the latest cuda platform, the first method could have better performance (as it would not block the host execution). After changing the synchronization method, I can get the following result
```
unprofile:  1.0506488879521687
unprofile:  1.064118226369222
unprofile:  1.0584275523821514
unprofile:  1.049544870853424
unprofile:  1.0260204474131267
unprofile:  1.0193662345409393
unprofile:  1.0525288979212444
unprofile:  1.014520029226939
unprofile:  1.0107475121815999
unprofile:  1.0137599905331929
profile:  1.0360222061475117
profile:  1.0414480169614155
profile:  1.048724373181661
profile:  1.048232873280843
profile:  1.051284392674764
profile:  1.0464515686035156
profile:  1.032240907351176
profile:  1.0401893456776936
profile:  1.0287200212478638
profile:  1.0413697361946106
```

This change should allow ios to have better end-to-end performance compared with other frameworks in the new version of cuda.

**Comment by Lucas890512** [comment]
Yeah, that makes sense, since I am using cuda 11.0 (since rtx30 series only support 11.0 or higher) as you said. 

So, if I want to get the best result of IOS. I'd better run both `profile_stage=true` and `profile_stage=false`, then pick the smaller one. Is that correct?

**Comment by yaoyaoding** [comment]
Yes, you can select the better one between proflie_stage=true/false.

**Comment by Lucas890512** [comment]
Okay, thx, really appreciate your help!
