### ISSUE TITLE
How do you deal with the operator execution?

### ISSUE THREAD

**Issue by WuZheng326** [mit-han-lab/inter-operator-scheduler#14]
I notice that you have two runtime code. One is ios_runtime.cu and another is trt_runtime.cc. So do you use cudnn to execute the ops or you convert the ios graph to tensorRT graph and let tensorRT to execute your graph?

**Comment by yaoyaoding** [comment]
IOS directly uses cuDNN library in IOS runtime (ios_runtime.cu). TensorRT runtime is used for comparison with IOS.

**Comment by WuZheng326** [comment]
ok，thank you
