### ISSUE TITLE
What should I do if I want to run IOS system on A100?

### ISSUE THREAD

**Issue by kingshentan** [mit-han-lab/inter-operator-scheduler#17]
Hi,
I read the file experiments/latency/main.py and found that IOS only supports ['1080ti', '1080', 'v100', 'titanxp', '2080ti', 'cpu', 'k80']. 
If I want IOS to run on A100, do I just add "a100" to the above list?

**Comment by yaoyaoding** [comment]
Hi @kingshentan,

You do not need to add "a100" to the list to run IOS on A100. The argument is only used to record the experiments. Say, you can run on A100 but give IOS the tag 1080ti. But of course, you could add a new tag for your gpu to avoid confusion.

**Comment by fengyuICT** [comment]
> Hi @kingshentan,
> 
> You do not need to add "a100" to the list to run IOS on A100. The argument is only used to record the experiments. Say, you can run on A100 but give IOS the tag 1080ti. But of course, you could add a new tag for your gpu to avoid confusion.

OK. Thanks!
