### ISSUE TITLE
What should I do if I want to run IOS system on a specific gpu? 

### ISSUE THREAD

**Issue by KAIWEILIUCC** [mit-han-lab/inter-operator-scheduler#18]
Hi,

If I want to run IOS system on my server, which has more than one GPUs and I would like to specify a gpu for it, what should I do? :)

**Comment by yaoyaoding** [comment]
Hi @KAIWEILIUCC,

You can try setting the `CUDA_VISIBLE_DEVICES` envrioment variable. See [here](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/).

**Comment by KAIWEILIUCC** [comment]
Thank you!
