### ISSUE TITLE
Can models be imported from other formats?

### ISSUE THREAD

**Issue by KAIWEILIUCC** [mit-han-lab/inter-operator-scheduler#19]
Hello,

In this framework, whether the model can only be built manually? Can I import from any other formats? Thank you very much! :)

**Comment by yaoyaoding** [comment]
Hi @KAIWEILIUCC,

This repo is just a prototype of our idea, and it is not intended to be used in practice. Thus, we did not add the support of importing from other formats. If you want to compare IOS with your or other framework on the models not included in our experiments, you might want to implement the model using IOS's graph construction API.

**Comment by KAIWEILIUCC** [comment]
OK. Thank you very much!
