### ISSUE TITLE
parallel execution increases the latency when using "nasnet_large(6,32)" in some condition

### ISSUE THREAD

**Issue by Lucas890512** [mit-han-lab/inter-operator-scheduler#20]
hey, I have an interesting problem here.

In two different environments, the same code gives opposite result when scheduling `ios.models.nasnet_large(6,32)`.
In `gtx1060 and cuda 10.2`, the latency of sequential schedule is `11.63ms` and the latency of parallel is `8.162ms`.
While in `rtx3080 and cuda 11.1`, the latency of sequential schedule is `9.174ms` and the latency of parallel is `11.904ms`. 

At first I wonder maybe the condition is similar to the `se_net example` in the paper. Then I use `IOS schedule` to replace greedy schedule, the latency of parallel is still longer than sequential.

The code is:
```python
import ios
import numpy as np

graph=ios.models.nasnet_large(6,32)
graph.sequential_schedule()
l_seq = 0
for i in range(10):
    latency = ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6)
    print(f' Sequential schedule: {np.mean(latency):.3f} ms')
    l_seq += np.mean(latency)
l_seq /= 10

graph.greedy_schedule(8)

l_mul = 0
for i in range(10):
    latency = ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6)
    print(f' greedy schedule: {np.mean(latency):.3f} ms')
    l_mul += np.mean(latency)
l_mul /= 10

print('latency_seq: ', round(l_seq, 3), 'ms')
print('latency_greedy: ', round(l_mul, 3), 'ms')
print('inference speedup ' + str(round(l_seq / l_mul, 3)) + 'x')

```

**Comment by yaoyaoding** [comment]
Hi @Lucas890512,

Is it possible to run the cuda 10.2 (cudnn 7) on rtx3080 GPU? 

I have observed some performance degradation in parallel schedule when people use cudnn 8+ on GPU with new arch ( see [here](https://github.com/mit-han-lab/inter-operator-scheduler/issues/10#issuecomment-1111480707)):

> Besides that, I found the new version (e.g., 8) of cuDNN is not good at multi-stream execution as the old version (e.g., 7.6.5), so you might need to use the old version of cuDNN to achieve better performance. I suspect the reason is that the new cuDNN has some optimization that would trigger device synchronization (e.g., [using different cache/shared mem partition policies](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXECUTION.html#group__CUDART__EXECUTION_1g6699ca1943ac2655effa0d571b2f4f15) for different kernels, which is used in cutlass). Using the kernels (e.g., from TVM) that do not rely on this optimization should be fine.

**Comment by Lucas890512** [comment]
hi @yaoyaoding , 

Rtx30s GPU only supports cuda 11.1 or higher. If the problem results from the cuda version, I can solve it by rent a server or just buy a card. It's all fine.

Well i'm curious about the difference between using `ios.models.nasnet_large(6,32)` and `ios.models.nasnet_large(96,168)` (the default one). Parallel execution works well in the latter condition but fails the former. 

Is there some reason? The computation cost of a conv in the former condition is decreased, but it is still comparable with `inception_v3`. By the way, both ios and greedy performs well on `inception_v3`.

**Comment by yaoyaoding** [comment]
The convolution type also matters. 

Parallelzing multiple kernels on NVIDIA GPU would benefit if these kernels have a small number of **thread blocks**. 
The nasnet uses seperate convolutions (depthwise + pointwise conv2d), while inception v3 uses tranditional convolutions. Although the sep conv usually has less computation than inception v3, but the number of thread blocks would not decrease (you might want to check this using nvidia nsight system/compute). Thus, a simple rule to check whether we have speedup on parallelizing multiple kernels is to check whether the number of the thread blocks in the original kernels could saturate the whole device.

In terms of your cases, 

> Well i'm curious about the difference between using ios.models.nasnet_large(6,32) and ios.models.nasnet_large(96,168) (the default one). Parallel execution works well in the latter condition but fails the former.

Did you try both cases in RTX 1080 with cudnn 7.6.5?

**Comment by Lucas890512** [comment]
> 

Yes, it is more appropriate to use the number of thread blocks required by kernels to see if we can benefit from parallel execution. 

Back to my problem. I said:
>Well i'm curious about the difference between using ios.models.nasnet_large(6,32) and ios.models.nasnet_large(96,168) (the default one). Parallel execution works well in the latter condition but fails the former.

The environment above is **rtx3080**.

And Yes, I use `ios` and `greedy` to schedule both the two kind of NASNet on **gtx1060** with cuda 10.2 and cudnn 7.6.5. The result shows that parallel execution can reduce the latency in all the cases.

**Comment by yaoyaoding** [comment]
> Well i'm curious about the difference between using ios.models.nasnet_large(6,32) and ios.models.nasnet_large(96,168) (the default one). Parallel execution works well in the latter condition but fails the former.

When we use parallel execution on cudnn 8+, there will be some pre-launch configuring that triggers the synhronization, which has a bad impact on the parallel execution performance. Besides, we used explicit sync between each stage of the schedule, which also has a bad impact on the parallel execution performance. Because there are such engineering-side penaty when using parallel execution, once the benefit coming from parallel execution can not outperform these penaty, we will not observe speedup. I believe that's why you observed that `ios.models.nasnet_large(6,32)` has a better performance for sequential schedule. 

One potential solution to address above mentioned penaty is to use CUDA graph, which gets more stable and efficient in  cuda 11+.

**Comment by Lucas890512** [comment]
okay. The most possible reason is that the newer version of cudnn introduces more sync overhead, which makes the speedup unobservable.

Thanks for your explanation, I will use cudnn 7.6.5 as the env..
