### ISSUE TITLE
[ios.trt_runtime]Question

### ISSUE THREAD

**Issue by Neo-Zhou1** [mit-han-lab/inter-operator-scheduler#21]
When I tested 'ios.trt_runtime' model before, and I met this question.
![1](https://user-images.githubusercontent.com/95663136/230290967-0f81f1e7-623e-43f3-98e7-de0a9e93db46.png)

Then I read the 'trt_runtime.py' and found that 
![2](https://user-images.githubusercontent.com/95663136/230291038-85acc647-b071-4f90-9062-b0ada7f307e9.png)

Does it mean when the program entrys this function it always raises this error? 

Or, it has something with my TensorRT's install?

**Comment by yaoyaoding** [comment]
Hi @Neo-Zhou1,

Did you build the IOS TensorRT runtime following [these insturctions](https://github.com/mit-han-lab/inter-operator-scheduler#411-install-tensorrt-runtime-in-ios)?

**Comment by Neo-Zhou1** [comment]
Hi, I'm glad to hear your reply. @yaoyaoding ,

In fact, I did build that follwing those insturction. But my cudnn version is 8.0 and TensorRT version is TensorRT-7.2.3.4 and TensorRT-7.2.2.3. I tested both of that before.

So, I think it may  affect my test. On the other hand, did conda and python environment possibly lead to this reslut？ 

Thanks for your suggestion.

**Comment by yaoyaoding** [comment]
Can you check
1. whether there is a `libtrt_runtime.so` after you build the runtime (step 4 of [here](https://github.com/mit-han-lab/inter-operator-scheduler#411-install-tensorrt-runtime-in-ios))
2. whether there is a `libtrt_runtime.so` in the ios package after installation (i.e., `/home/.../site-packages/ios-.../...`)?

**Comment by Neo-Zhou1** [comment]
Yes, libtrt_runtime.so was created when I build the runtime. However it didn't exist in the ios package after installation.

![3](https://user-images.githubusercontent.com/95663136/230544816-92a10a28-4a12-4e38-9c37-20c4b7295b87.png)

![4](https://user-images.githubusercontent.com/95663136/230544884-af05ce2e-6559-4891-bffa-0125cf0328d2.png)

**Comment by yaoyaoding** [comment]
Could you try to uninstall ios package and reinstall it with the instructions in [here](https://github.com/mit-han-lab/inter-operator-scheduler#411-install-tensorrt-runtime-in-ios)?

If it does not work, you can print out the `existing_libs` in [setup.py](https://github.com/mit-han-lab/inter-operator-scheduler/blob/master/python/setup.py) to check whether `libtrt_runtime.so` has been detected.

**Comment by Neo-Zhou1** [comment]
Thank you very much for you suggestion!

It worked correctly after I uninstalled ios package and reinstalled it.

**Comment by Neo-Zhou1** [comment]
Thank you very much for your suggestions!

It worked correctly after I uninstalled ios package and reinstalled it.
