### ISSUE TITLE
About GeoMean

### ISSUE THREAD

**Issue by kumazzu** [mit-han-lab/inter-operator-scheduler#22]
Hi, 
I found that a CNN called GeoMean was evaluated in your experiment, but I could not find information about this model in /python/ios/models. I know nothing about this model, could you tell me something about it?

**Comment by yaoyaoding** [comment]
Hi @kumazzu,

Sorry for the confusion. The GeoMean means [geometric mean](https://en.wikipedia.org/wiki/Geometric_mean) of the performance on all benchmark models. We use it to compare the overall performance of different schedules/baselines.

**Comment by kumazzu** [comment]
Thank u very much!
