### ISSUE TITLE
An interesting find in the experimental result

### ISSUE THREAD

**Issue by ikaroso** [mit-han-lab/inter-operator-scheduler#24]
According to the paper, in the End-to-End performance comparison of different frameworks, it seems that on `NAS-Net`, the performance of TensorRT is worse than TensorFlow (using V100 or rtx2080ti). 

This is interesting because intuitively, I think TensorRT should at least has a better performance than Tensorflow.
![image](https://github.com/mit-han-lab/inter-operator-scheduler/assets/49864758/1ee7adbc-ec5c-4c85-8af9-e16dc7d164c9)

Thus, I compared the latency performance of `Sequential Scheduling` and `TensorRT` by using IOS framework. The result shows that the latency of `TensorRT` (17.4ms in avg) is slightly worse than the latency of `Sequential Scheduling` (16.4ms in avg). This result consist with your experiment result in the `readme.md`.

This is also interesting. To my understanding (may not be correct), IOS-runtime uses CuDNN APIs to create CUDA kernels and execute the whole CNN. To execute the same CNN, the CNN described in IOS-IR is translated to a `TensorRT` graph. Since `TensorRT` employs optimizations including fusion, auto-tuning, etc.. 
I suppose that `TensorRT` should have a better latency performance than `Sequential Scheduling`?

However, `NAS-Net` is the special case where `TensorRT` fails.
Do you think the reason may come from the structure or operator types of NAS-Net?

**Comment by yaoyaoding** [comment]
Hi @ikaroso, I do not know why TensorRT is slower than Tensorflow on NasNet. You might want to use nsight system to profile and see what happened.

**Comment by ikaroso** [comment]
hey @yaoyaoding  thx, I will try to figure out what happened.
