### ISSUE TITLE
fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by caiyu6666** [mit-han-lab/inter-operator-scheduler#3]
When rebuild IOS runtime and TRT runtime, I run "make -j4" but it gets the error `fatal error: NvInfer.h: No such file or directory`. There is no such file named "NvInfer.h". How to solve it?

**Comment by caiyu6666** [comment]
oooo, I have solved it.
Add ```include_directories(/you/path/TensorRT-7.0.0.11/include)``` and ```link_directories(/you/path/TensorRT-7.0.0.11/lib)``` to `CMakeLists.txt` and it will be ok.

**Comment by yaoyaoding** [comment]
Cool. You can also try adding the TensorRT path to config.cmake file (at line 8) and rebuild (cmake & make).
