### ISSUE TITLE
Failure on CUDA11.1

### ISSUE THREAD

**Issue by marsupialtail** [mit-han-lab/inter-operator-scheduler#4]
On CUDA 11.1, python sample.py gives following error:
Cuda failure: 222 the provided PTX was compiled with an unsupported toolchain.
/home/ubuntu/ios/src/ios/ios_runtime.cu:1332
Aborting...

**Comment by yaoyaoding** [comment]
Hi, according to this [post](https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292), it is likely that your compilation toolchain is not compatible with the driver. Can you try with a consistent driver and cuda toolkit? 

Best

**Comment by yaoyaoding** [comment]
Please reopen the issue if this does not resolve the problem.
