### ISSUE TITLE
error

### ISSUE THREAD

**Issue by heart1998** [mit-han-lab/inter-operator-scheduler#5]
No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/xu/build/ios/build/CMakeFiles/CMakeOutput.log".
See also "/home/xu/build/ios/build/CMakeFiles/CMakeError.log".

**Comment by yaoyaoding** [comment]
Hi, it seems that cmake can not find cuda compiler `nvcc` automatically. You can try one of the following resolutions:
- Add `SET(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)` to `CMakeLists.txt`,
- or, set the environment variable `CUDACXX` to point to your nvcc compiler.
- or, add `/usr/local/cuda/bin` to your PATH.

**Comment by yaoyaoding** [comment]
Please reopen the issue if it can not resolve the problem.
