### ISSUE TITLE
AttributeError: /home/u/.local/lib/python3.7/site-packages/ios-0.1.dev0-py3.7.egg/ios/contrib/../libios_runtime.so: undefined symbol: stage_latency

### ISSUE THREAD

**Issue by cv-programmer** [mit-han-lab/inter-operator-scheduler#6]
hI, I follow your steps step by step to install. Because there is no CUDA, I set CUDA in cmake to OFF, and cmake and make succeed. Then I execute Python setup.py. However, when I execute Python sample.py, there are the following errors "AttributeError: /home/u/.local/lib/python3.7/site-packages/ios-0.1.dev0-py3.7.egg/ios/contrib/../libios_ runtime.so: undefined symbol: stage_ "Latency", can you help me solve it? Thank you very much!
My software version is as follows:
gcc:7.5.0, g++: 7.5.0, make: 4.1, cmake: 3.10.2, python: 3.7.11

**Comment by yaoyaoding** [comment]
Hi @cv-programmer, IOS [requires](https://github.com/mit-han-lab/inter-operator-scheduler#21-prerequisites) CUDA toolkit and cuDNN to work properly.

**Comment by cv-programmer** [comment]
Thank you for your help
