### ISSUE TITLE
Which part of code is related to the parallel execution of operators (set CUDA streams)?

### ISSUE THREAD

**Issue by puddingfjz** [mit-han-lab/inter-operator-scheduler#7]
Hi, 

I am trying to get some help of writing the code to set cuda streams and run different operators concurrently from your code. 
May I ask which part of code is related to the parallel execution of operators (set CUDA streams)?

Thanks!

**Comment by yaoyaoding** [comment]
Hi,

Sorry for the late response.

In our implementation, multiple cudnn contexts are created and each is associated with a specific cuda stream. [Here](https://github.com/mit-han-lab/inter-operator-scheduler/blob/master/src/ios/ios_runtime.cu#L138) is the creation of cuda stream and cuda context.

Please let me know if you have other questions.

**Comment by puddingfjz** [comment]
Hi, 

Thanks a lot for your reply!
