### ISSUE TITLE
When no parallelism is used, can I change the actual executing order of nodes by reordering Block.stages?

### ISSUE THREAD

**Issue by ikaroso** [mit-han-lab/inter-operator-scheduler#9]
Hi, love your work very much

i have a problem here.
For example, we got a graph like this:

Sequential(
  [1]Conv2d(0)
  [2]Conv2d(0)
  [3]Conv2d(0)
  [4]Conv2d(1)
  [5]Concat(4,2,3)
)
it has only one block and **block.stages** is [ [['1']], [['2']], [['3']], [['4']], [['5']] ].
obviously, the execution order of node [1], [2], [3] can be changed and the result of this CNN won't change.

**My question** is that, if I change the **block.stages** to [ [['3']], [['2']], [['1']], [['4']], [['5']] ], will the nodes' actual execution order in the GPU be changed too?

i'm trying to get the answer from ios_runtime.cu, but CUDA code is kinda difficult for me.

**Comment by yaoyaoding** [comment]
Hi @ikaroso,

Thanks for your interest in our work. The answer is Yes, the actual execution order will change from 1, 2, 3, 4, 5 to 3, 2, 1, 4, 5 if you change the block stages. Generally, IOS runtime executes the model like this:

> stage 1
> device sync
> stage 2
> device sync
> ...
> device sync
> stage n

**Comment by ikaroso** [comment]
Thanks for your reply !
